version: "3"

services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    expose:
      - "5000"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot:6.2.0-nginx1.31.3
    restart: always
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d:ro
    depends_on:
      - myportfolio

volumes:
  mydatabase:
  nginx_secrets:
